title: Carlos Segarra
url: "https://carlossegarra.com"
#myurl: "https://carlossegarra.com"
myurl: "http://localhost:3000"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://carlossegarra.com/"
footer_text: "Last update: 09/09/2020"
favicon_location: 'favicon.ico'

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "/assets/SegarraCarlos_CV.pdf"
 - name: "Contact"
   link: "/contact"

social-media:
  - id: 'carlos@carlossegarra.com'
    href: 'mailto:'
    title: 'Email'
    fa-icon: 'fa-envelope-square'
  
  - id: 'carlossegarrag'
    href: 'https://www.twitter.com/'
    title: 'Twitter'
    fa-icon: 'fa-twitter-square'
  
  - id: 'csegarragonz'
    href: 'https://github.com/'
    title: 'GitHub'
    fa-icon: 'fa-github-square'

  - id: 'carlossegarrag'
    href: 'https://linkedin.com/in/'
    title: 'LinkedIn'
    fa-icon: 'fa-linkedin'

  - id: 'citations?user=U0KR_0cAAAAJ&hl=en'
    href: 'https://scholar.google.com/'
    title: 'Google Scholar'
    fa-icon: 'fa-university'

