name: Build artifacts

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-web:
    runs-on: ubuntu-20.04
    steps:
      - name: "Get the code"
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Build the web container"
        uses: docker/build-push-action@v2
        with:
          push: false
          file: Dockerfile
          build-args:
            - JEKYLL_VERSION=4
          context: .
          tags: csegarragonz/web
