name: "Build and deploy the website"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

defaults:
  run:
    shell: bash

jobs:
  deploy-web:
    runs-on: self-hosted
    steps:
      - name: "Get the code"
        uses: actions/checkout@v4
      - name: "Get tag version"
        run: echo "TAG_VERSION=$(cat ./VERSION)" >> $GITHUB_ENV
      - name: "Update the last updated date"
        run: |
          ./bin/inv_wrapper.sh update.last-modified
          cat _config.yml | grep "Last update:"
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2
      - name: "Build the web container"
        uses: docker/build-push-action@v3
        with:
          push: false
          file: Dockerfile
          build-args: JEKYLL_VERSION=4
          context: .
          tags: csegarragonz/web:${{ env.TAG_VERSION }}
      - name: "Remove running versions of the contianer"
        run: docker rm -f live-web
      - name: "Deploy the website"
        run: python3 deploy_entrypoint.py
      - name: "Assert that the container is running"
        run: |
          sleep 5
          [ "$( docker container inspect -f '{{.State.Running}}' live-web )" = "true" ]
