name: "Renew HTTPS certs"

on:
  schedule:
    # Run at 3:00 AM on the 1st day of every month
    - cron: '0 3 1 * *'
  workflow_dispatch:

jobs:
  renew-certs:
    runs-on: self-hosted
    env:
      DOMAIN: carlossegarra.com

    steps:
    - uses: actions/checkout@v6

    - name: "Stop web container"
      run: docker rm -f live-web

    - name: "Renew certs"
      run: sudo certbot renew --standalone

    - name: "Run container again"
      run: python3 ./deploy_entrypoint.py
